apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: arc-sshd
  name: arc-sshd
spec:
  replicas: 1
  selector:
    matchLabels:
      run: arc-sshd
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: arc-sshd
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.count
                operator: DoesNotExist
      containers:
      - name: arc-sshd
        image: images.canfar.net/skaha-system/sshd:0.1
        imagePullPolicy: Always
        #imagePullPolicy: IfNotPresent
        #command: ["/bin/sh"]
        #args: ["-c", "while true; do sleep 10;done"] 
        resources:
          requests:
            memory: "4Gi"
            cpu: "1"
          limits:
            memory: "8Gi"
            cpu: "4"
        ports:
        - containerPort: 64022
          protocol: TCP
        volumeMounts:
        - mountPath: "/cavern"
          name: arc-ceph-volume
          subPath: cavern
        - mountPath: /etc/ssh/sshd_config
          name: arc-sshd-config-vol
          subPath: sshd_config
        - mountPath: /etc/ssh/ssh_host_ecdsa_key.pub
          name: arc-sshd-config-vol
          subPath: ssh_host_ecdsa_key.pub
        - mountPath: /etc/ssh/ssh_host_ed25519_key.pub
          name: arc-sshd-config-vol
          subPath: ssh_host_ed25519_key.pub
        - mountPath: /etc/ssh/ssh_host_rsa_key.pub
          name: arc-sshd-config-vol
          subPath: ssh_host_rsa_key.pub
        - mountPath: /etc/ssh/ssh_host_ecdsa_key
          name: ssh-host-ecdsa-key
          subPath: ssh_host_ecdsa_key
        - mountPath: /etc/ssh/ssh_host_ed25519_key
          name: ssh-host-ed25519-key
          subPath: ssh_host_ed25519_key
        - mountPath: /etc/ssh/ssh_host_rsa_key
          name: ssh-host-rsa-key
          subPath: ssh_host_rsa_key
        - mountPath: /var/lib/sss/pipes
          name: sssd-dir
          readOnly: true
      securityContext:
        runAsUser: 0
      priorityClassName: uber-user-preempt-high
      serviceAccountName: skaha
      volumes:
      - name: arc-ceph-volume
        cephfs:
          monitors:
          - 10.30.201.3:6789
          - 10.30.202.3:6789
          - 10.30.203.3:6789
          path: /volumes/_nogroup/054e398e-a08e-425e-9f7c-fc394362e38e
          user: keel_prod
          secretRef:
            name: cephfs-cephx-key
          readOnly: false
      - name: arc-sshd-config-vol
        configMap:
          name: arc-sshd-config
      - name: ssh-host-ecdsa-key
        secret:
          secretName: arc-sshd-priv1-secret
          defaultMode: 256
      - name: ssh-host-ed25519-key
        secret:
          secretName: arc-sshd-priv2-secret
          defaultMode: 256
      - name: ssh-host-rsa-key
        secret:
          secretName: arc-sshd-priv3-secret
          defaultMode: 256
      - name: sssd-dir
        hostPath:
          path: /var/lib/ubernetes
          type: Directory
