{{- range $secretIndex, $secretName := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretIndex }}
  namespace: {{ $.Values.skaha.namespace }}
type: Opaque
data:
  {{- range $certKey, $certValue := . }}
    {{ $certKey }}: {{ $certValue | quote }}
  {{- end }}
{{- end }}
