logLevel: warn

#adminPassword: "changeme"

externalURL: https://images.opencadc.org

containerSecurityContext:
  runAsGroup: 1001
  runAsNonRoot: true

podSecurityContext:
  fsGroup: 1001

exposureType: ingress

#***************************************************
ingress:

  core:
    hostname: images.opencadc.org
    annotations:
      kubernetes.io/ingress.class: traefik
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/proxy-body-size: "0"
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.certresolver: "cadc_cloudflare"
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      nginx.ingress.kubernetes.io/ssl-redirect: null
      nginx.ingress.kubernetes.io/proxy-body-size: null
    extraTls:
    - hosts:
        - images.opencadc.org

  notary:
    hostname: notary.opencadc.org
    annotations:
      kubernetes.io/ingress.class: traefik
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/proxy-body-size: "0"
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.certresolver: "cadc_cloudflare"
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      nginx.ingress.kubernetes.io/ssl-redirect: null
      nginx.ingress.kubernetes.io/proxy-body-size: null
    extraTls:
    - hosts:
        - notary.opencadc.org

#***************************************************
notary:
  enabled: true

  server:
    image:
      registry: docker.io
      repository: bitnami/harbor-notary-server-archived
      tag: 2.7.1-debian-11-r6
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: skaha.opencadc.org/node-type
              operator: In
              values:
              - service-node

  signer:
    image:
      registry: docker.io
      repository: bitnami/harbor-notary-signer-archived
      tag: 2.7.1-debian-11-r6
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: skaha.opencadc.org/node-type
              operator: In
              values:
              - service-node

#***************************************************
portal:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: skaha.opencadc.org/node-type
            operator: In
            values:
            - service-node

#***************************************************
core:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: skaha.opencadc.org/node-type
            operator: In
            values:
            - service-node

#***************************************************
jobservice:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: skaha.opencadc.org/node-type
            operator: In
            values:
            - service-node

#***************************************************
registry:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: skaha.opencadc.org/node-type
            operator: In
            values:
            - service-node

#***************************************************
chartmuseum:
  image:
    registry: docker.io
    repository: bitnami/chartmuseum-archived
    tag: 0.15.0-debian-11-r79
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: skaha.opencadc.org/node-type
            operator: In
            values:
            - service-node

#***************************************************
trivy:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: skaha.opencadc.org/node-type
            operator: In
            values:
            - service-node

#***************************************************
persistence:
  enabled: true

  persistentVolumeClaim:
    registry:
      existingClaim: ""
      storageClass: ""
      subPath: "harbor-registry"
      accessMode: ReadWriteOnce
      size: 1000Gi

    jobservice:
      existingClaim: ""
      storageClass: ""
      subPath: "harbor-jobservice"
      accessMode: ReadWriteOnce
      size: 10Gi

    chartmuseum:
      existingClaim: ""
      storageClass: ""
      subPath: "harbor-chartmuseum"
      accessMode: ReadWriteOnce
      size: 40Gi

    trivy:
      existingClaim: ""
      storageClass: ""
      accessMode: ReadWriteOnce
      size: 40Gi

  imageChartStorage:
    disableredirect: true

#***************************************************
postgresql:
  enabled: true

  persistence:
    enabled: true
    storageClass: ""
    subPath: harbor-postgresql

  primary:
    priorityClassName: uber-user-preempt-high
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: skaha.opencadc.org/node-type
              operator: In
              values:
              - service-node
    volumes:
      - name: postgresql-extended-config
        configMap:
          name: cadc-harbor-postgresql-extended-configuration
          defaultMode: 0640
      - name: custom-init-scripts
        configMap:
          name: cadc-harbor-postgresql-init-scripts
          defaultMode: 0640

    extraVolumeMounts:
      - name: writableconf
        mountPath: /opt/bitnami/postgresql/conf
      - name: writableconfd
        mountPath: /opt/bitnami/postgresql/conf/conf.d
      - name: writabletmp
        mountPath: /opt/bitnami/postgresql/tmp
    extraVolumes:
      - name: writableconf
        emptyDir: {}
      - name: writableconfd
        emptyDir: {}
      - name: writabletmp
        emptyDir: {}



#***************************************************
redis:
  enabled: true

  master:
    priorityClassName: uber-user-preempt-high
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: skaha.opencadc.org/node-type
              operator: In
              values:
              - service-node
    persistence:
      enabled: true
      storageClass: ""
      subPath: harbor-redis

  slave:
    persistence:
      enabled: true
      storageClass: "csi-cinder-sc-delete"
      subPath: harbor-redis