apiVersion: v1
kind: Service
metadata:
  name: posix-mapper-postgres
  namespace: {{ .Values.skaha.namespace }}
  labels:
    app: posix-mapper-postgres
spec:
  ports:
    - port: 5432
  selector:
    app: posix-mapper-postgres