---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    canfar-net-sessionID: "${skaha.sessionid}"
    canfar-net-sessionName: "${skaha.sessionname}"
    canfar-net-sessionType: "${skaha.sessiontype}"
    canfar-net-userid: "${skaha.userid}"
  name: "${skaha.jobname}"
spec:
  activeDeadlineSeconds: ${skaha.sessionexpiry}
  ttlSecondsAfterFinished: 86400
  template:
    metadata:
      labels:
        canfar-net-sessionID: "${skaha.sessionid}"
        canfar-net-sessionName: "${skaha.sessionname}"
        canfar-net-sessionType: "${skaha.sessiontype}"
        canfar-net-userid: "${skaha.userid}"
        job-name: "${skaha.jobname}"
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      restartPolicy: OnFailure
      ${skaha.schedulegpu}
      imagePullSecrets:
        - name: "${software.imagesecret}"
      securityContext:
        runAsUser: ${skaha.posixid} 
        runAsGroup: ${skaha.posixid}
        fsGroup: ${skaha.posixid}
        supplementalGroups: [${skaha.supgroups}]
      priorityClassName: uber-user-preempt-medium
      hostname: "${software.hostname}"
      initContainers:
      - name: backup-original-passwd-groups
        image: ${software.imageid}
        command: ["/bin/sh", "-c", "cp /etc/passwd /etc-passwd/passwd-orig && cp /etc/group /etc-group/group-orig"]
        volumeMounts:
        - mountPath: "/etc-passwd"
          name: etc-passwd
        - mountPath: "/etc-group"
          name: etc-group
      - name: init-users-groups
        image: images.opencadc.org/library/cadc-tomcat:1
        command: ["/init-users-groups/init-users-groups-from-service.sh"]
        volumeMounts:
        - mountPath: "/etc-passwd"
          name: etc-passwd
        - mountPath: "/etc-group"
          name: etc-group
        - mountPath: "/init-users-groups"
          name: init-users-groups
        - mountPath: "${SKAHA_TLD}"
          name: cavern-volume
          subPath: "cavern"
        {{- with .Values.deployment.skaha.extraVolumeMounts }}
        {{- range $mount := . }}
        {{- if eq $mount.mountPath "/config/cacerts" }}
        - mountPath: "/etc/pki/ca-trust/source/anchors/"
          name: {{ $mount.name }}
          {{ if $mount.readOnly }}
          readOnly: {{ $mount.readOnly }}
          {{ end }}
        {{ else }}
        {{- toYaml . | nindent 8 }}
        {{ end }}
        {{- end }}
        {{- end }}
        env:
        - name: HOME
          value: "${SKAHA_TLD}/home/${skaha.userid}"
        - name: POSIX_MAPPER_URI
          value: ${POSIX_MAPPER_URI}
        - name: REGISTRY_URL
          value: ${REGISTRY_URL}
        securityContext:
          runAsUser: 8675309
          runAsGroup: ${skaha.posixid}
{{- with .Values.deployment.extraHosts }}
      hostAliases:
{{- range $extraHost := . }}
        - ip: {{ $extraHost.ip }}
          hostnames:
            - {{ $extraHost.hostname }}
{{- end }}            
{{- end }}
      containers:
      - name: "${skaha.jobname}"
        env:
        - name: skaha_hostname
          value: "${skaha.hostname}"
        - name: skaha_username
          value: "${skaha.userid}"
        - name: JUPYTER_TOKEN
          value: "${skaha.sessionid}"
        - name: JUPYTER_CONFIG_DIR
          value: "${SKAHA_TLD}/home/${skaha.userid}/.jupyter/"
        - name: JUPYTER_DATA_DIR
          value: "${SKAHA_TLD}/home/${skaha.userid}/.local/share/jupyter/"
        - name: JUPYTER_RUNTIME_DIR
          value: "${SKAHA_TLD}/home/${skaha.userid}/.local/share/jupyter/runtime/"
        - name: JUPYTER_PATH
          value: "${SKAHA_TLD}/home/${skaha.userid}/.jupyter/"
        - name: JUPYTERLAB_WORKSPACES_DIR
          value: "${SKAHA_TLD}/home/${skaha.userid}/.jupyter/lab/workspaces/"
        - name: JUPYTERLAB_SETTINGS_DIR
          value: "${SKAHA_TLD}/home/${skaha.userid}/.jupyter/lab/user-settings/"
        - name: NB_USER
          value: "${skaha.userid}"
        - name: NB_UID
          value: "${skaha.posixid}"
        - name: HOME
          value: "${SKAHA_TLD}/home/${skaha.userid}"
        - name: PWD
          value: "${SKAHA_TLD}/home/${skaha.userid}"
        - name: XDG_CACHE_HOME
          value: "${SKAHA_TLD}/home/${skaha.userid}"
        - name: JULIA_NUM_THREADS
          value: "${software.requests.cores}"
        - name: OPENBLAS_NUM_THREADS
          value: "${software.requests.cores}"
        - name: MKL_NUM_THREADS
          value: "${software.requests.cores}"
        - name: OMP_NUM_THREADS
          value: "${software.requests.cores}"
        image: ${software.imageid}
        command: ["/skaha-system/start-jupyterlab.sh"]
        args:
        - ${skaha.sessionid}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "${software.requests.ram}"
            cpu: "${software.requests.cores}"
            ephemeral-storage: "20Gi"
          limits:
            memory: "${software.limits.ram}"
            cpu: "${software.limits.cores}"
            nvidia.com/gpu: "${software.limits.gpus}"
            ephemeral-storage: "200Gi"
        ports:
        - containerPort: 8888
          protocol: TCP
          name: notebook-port
        volumeMounts:
        - mountPath: "/etc/passwd"
          name: etc-passwd
          subPath: passwd
        - mountPath: "/etc/group"
          name: etc-group
          subPath: group
        - mountPath: "/skaha-system"
          name: start-jupyterlab
        - mountPath: "${SKAHA_TLD}"
          name: cavern-volume
          subPath: "cavern"
        - mountPath: "/scratch"
          name: scratch-dir
          subPath: "${skaha.sessionid}"
        securityContext:
          runAsUser: ${skaha.posixid}
          runAsGroup: ${skaha.posixid}
          allowPrivilegeEscalation: false
      volumes:
      - name: start-jupyterlab
        configMap:
          name: launch-scripts
          defaultMode: 0777
      - name: init-users-groups
        configMap:
          name: init-users-groups-config
          defaultMode: 0777
      - name: cavern-volume
        persistentVolumeClaim:
          claimName: skaha-workload-cavern-pvc
      - name: scratch-dir
        emptyDir: {}
      - name: etc-group
        emptyDir: {}
      - name: etc-passwd
        emptyDir: {}
      {{- with .Values.deployment.skaha.extraVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
