apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: carta-ingress
  namespace: arcade-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /carta/$2
spec:
  rules:
  - host: proto.canfar.net
    http:
      paths:
      - path: /carta(/|$)(.*)
        backend:
          serviceName: arcade-wsproxy-svc
          servicePort: 8080
