apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: desktop-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /desktop/$2
spec:
  rules:
  - host: rc-uv.canfar.net
    http:
      paths:
      - path: /desktop(/|$)(.*)
        backend:
          serviceName: skaha-wsproxy-svc
          servicePort: 8080
