apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: skaha-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /skaha/$2
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "optional"
    nginx.ingress.kubernetes.io/auth-tls-secret: "development/all-cacert"
#    nginx.ingress.kubernetes.io/auth-tls-secret: "development/gridcanada-cacert"
#    nginx.ingress.kubernetes.io/auth-tls-secret: "cadc-cacert"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "10"
#    nginx.ingress.kubernetes.io/auth-tls-error-page: "https://www.canfar.net"
#    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "false"
    nginx.ingress.kubernetes.io/proxy_set_header: X-Client-Certificate $ssl_client_escaped_cert
spec:
  tls:
  - hosts:
    - ws-uv.canfar.net
    secretName: canfar-net-cert-secret
  rules:
  - host: ws-uv.canfar.net
    http:
      paths:
      - path: /skaha(/|$)(.*)
        backend:
          serviceName: skaha-tomcat-svc
          servicePort: 8080
