apiVersion: v1
kind: Service
metadata:
  name: storage-ui-tomcat-svc
  namespace: {{ .Values.skaha.namespace }}
  labels:
    run: storage-ui-tomcat-svc
spec:
  ports: 
  - port: 8080
    name: http-connection
    protocol: TCP
  {{ with .Values.service }}
    {{ with .reg }}
      {{ with .extraPorts }}
  {{- toYaml . | nindent 2 }}
      {{- end }}
    {{- end }}
  {{- end }}
  selector:
    run: storage-ui-tomcat
