kubernetesClusterDomain: cluster.local
skaha:
  namespace: skaha-system
skahaWorkload:
  namespace: skaha-workload
  
secrets:
  # default-certificate:  # Match the default-certificate name in traefik.tlsStore.default.defaultCertificate.secretName
  # For server domains with self-signed certificates, add the Base64 encoded file content here.
    # tls.crt: <base64 encoded server cert>
    # tls.key: <base64 encoded server key>

# Don't install Traefik by default.  Set to true to add it in.  Omitting it defaults to true, so beware.
traefik:
  install: false
  logs:
    general:
      # -- By default, the logs use a text format (common), but you can
      # also ask for the json format in the format option
      # format: json
      # By default, the level is set to ERROR.
      # -- Alternative logging levels are DEBUG, PANIC, FATAL, ERROR, WARN, and INFO.
      level: ERROR
    access:
      # -- To enable access logs
      enabled: false
  # tlsStore:
  #   default:
  #     defaultCertificate:
  #       # See default-certificate secret(s) above
  #       secretName: default-certificate
  # tlsOptions:
  #   traefik-client-cert-option:
  #     clientAuth:
  #       clientAuthType: VerifyClientCertIfGiven
  #       secretNames:
  #         - cacert-secret
