---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    canfar-net-sessionID: "${arcade.sessionid}"
    canfar-net-sessionName: "${arcade.sessionname}"
    canfar-net-sessionType: "${arcade.sessiontype}"
    canfar-net-userid: "${arcade.userid}"
  name: "${arcade.jobname}"
spec:
  template:
    metadata:
      labels:
        canfar-net-sessionID: "${arcade.sessionid}"
        canfar-net-sessionName: "${arcade.sessionname}"
        canfar-net-sessionType: "${arcade.sessiontype}"
        canfar-net-userid: "${arcade.userid}"
        job-name: "${arcade.jobname}"
    spec:
      restartPolicy: OnFailure
      #restartPolicy: Never
      containers:
      - name: "${arcade.jobname}"
        env:
        - name: HOME
          value: "/cavern/home/${arcade.userid}"
        - name: VNC_PW
          value: "${arcade.sessionid}"
        - name: arcade_hostname
          value: "${arcade.hostname}"
        - name: arcade_username
          value: "${arcade.userid}"
        securityContext:
          runAsUser: ${arcade.posixid} 
          runAsGroup: ${arcade.posixid}
        image: canfar-registry.cloud.computecanada.ca/arcade-desktop:latest
        #imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        #imagePullPolicy: Never
        ports:
        - containerPort: 5901
          protocol: TCP
          name: vnc-port
        - containerPort: 6901
          protocol: TCP
          name: novnc-port
        volumeMounts:
        - mountPath: "/cavern"
          name: cavern-volume
          subPath: "cavern"
        - mountPath: /var/lib/sss/pipes
          name: sssd-dir
          readOnly: true
      volumes:
      - name: cavern-volume
        persistentVolumeClaim:
          claimName: cavern-ceph-claim-20200608
      - name: sssd-dir
        hostPath:
          path: /var/lib/ubernetes
          type: Directory
