---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    canfar-net-sessionID: "${arcade.sessionid}"
    canfar-net-sessionName: "${arcade.sessionname}"
    canfar-net-sessionType: "${arcade.sessiontype}"
    canfar-net-userid: "${arcade.userid}"
  name: "${arcade.jobname}"
spec:
  template:
    metadata:
      labels:
        canfar-net-sessionID: "${arcade.sessionid}"
        canfar-net-sessionName: "${arcade.sessionname}"
        canfar-net-sessionType: "${arcade.sessiontype}"
        canfar-net-userid: "${arcade.userid}"
        job-name: "${arcade.jobname}"
    spec:
      restartPolicy: OnFailure
      #restartPolicy: Never
      containers:
      - name: "${arcade.jobname}"
        env:
        - name: arcade_hostname
          value: "${arcade.hostname}"
        - name: arcade_username
          value: "${arcade.userid}"
        - name: JUPYTER_TOKEN
          value: "${arcade.sessionid}"
        - name: JUPYTER_CONFIG_DIR
          value: "/home/jovyan"
        - name: JUPYTER_PATH
          value: "/home/jovyan"
        #- name: NB_USER
        #  value: "${arcade.userid}"
        #- name: NB_UID
        #  value: "${arcade.posixid}"
        #- name: NB_GROUP
        #  value: "${arcade.userid}"
        #- name: NB_GID
        #  value: "${arcade.posixid}"
        #- name: CHOWN_HOME
        #  value: "yes"
        securityContext:
          runAsUser: 0
          #runAsUser: ${arcade.posixid} 
          #runAsGroup: ${arcade.posixid}
        image: canfar-registry.cloud.computecanada.ca/arcade-notebook:latest
        #workingDir: "/cavern/home/${arcade.userid}"
        #command: ["start-notebook.sh"]
        #args:
        #- "--NotebookApp.base_url=notebook/${arcade.sessionid}"
        #- "--NotebookApp.notebook_dir=/cavern"
        command: ["/home/jovyan/arcade-start-notebook"]
        args:
          - ${arcade.userid}
          - ${arcade.sessionid}
        #imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        #imagePullPolicy: Never
        ports:
        - containerPort: 8888
          protocol: TCP
          name: notebook-port
        volumeMounts:
        - mountPath: "/cavern"
          name: cavern-volume
          subPath: "cavern"
        - mountPath: "/scratch"
          name: scratch-dir
          subPath: "${arcade.sessionid}"
        - mountPath: /var/lib/sss/pipes
          name: sssd-dir
          readOnly: true
      volumes:
      - name: cavern-volume
        cephfs:
          monitors:
          - 10.30.201.3:6789
          - 10.30.202.3:6789
          - 10.30.203.3:6789
          path: /volumes/_nogroup/dcd994bc-c0d4-4557-9fbf-28fc4ef5969e
          user: kanfarnetes_dev
          secretRef:
            name: cephfs-cephx-key
          readOnly: false          
      - name: scratch-dir
        emptyDir: {}
      - name: sssd-dir
        hostPath:
          path: /var/lib/ubernetes
          type: Directory
