apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-uws-postgres
  namespace: {{ .Values.skaha.namespace }}
  labels:
    app: {{ .Release.Name }}-uws-postgres
spec:
  ports:
    - port: 5432
  selector:
    app: {{ .Release.Name }}-uws-postgres