---
apiVersion: batch/v1
kind: Job
metadata:
  name: "${software.jobname}"
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: OnFailure
      #restartPolicy: Never
      containers:
      - name: "${software.containername}"
        command: ["/skaha-system/start-desktop-software.sh"]
        args:
        - ${skaha.userid}
        - ${software.containerparam}
        env:
        - name: HOME
          value: "/cavern/home/${skaha.userid}"
        - name: DISPLAY
          value: "${software.targetip}"
        - name: GDK_SYNCHRONIZE
          value: "1"
        - name: SHELL
          value: "/bin/bash"
        securityContext:
          runAsUser: ${skaha.posixid}
          runAsGroup: ${skaha.posixid}
          allowPrivilegeEscalation: false
        image: "${software.imageid}"
        workingDir: "/cavern/home/${skaha.userid}"
        imagePullPolicy: Always
        #imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6000
          protocol: TCP
        volumeMounts:
        - mountPath: "/skaha-system"
          name: start-desktop-software
        - mountPath: "/cavern/home"
          name: cavern-volume
          subPath: "cavern/home"
        - mountPath: "/scratch"
          name: scratch-dir
          subPath: "${skaha.sessionid}"
        - mountPath: "/cavern/projects"
          name: cavern-volume
          subPath: "cavern/projects"
        - mountPath: /var/lib/sss/pipes
          name: sssd-dir
          readOnly: true
      volumes:
      - name: start-desktop-software
        configMap:
          name: start-desktop-software
          defaultMode: 0744
      - name: cavern-volume
        cephfs:
          monitors:
          - 10.30.201.3:6789
          - 10.30.202.3:6789
          - 10.30.203.3:6789
          path: /volumes/_nogroup/dcd994bc-c0d4-4557-9fbf-28fc4ef5969e
          user: kanfarnetes_dev
          secretRef:
            name: cephfs-cephx-key
          readOnly: false          
      - name: scratch-dir
        emptyDir: {}
      - name: sssd-dir
        hostPath:
          path: /var/lib/ubernetes
          type: Directory
