apiVersion: apps/v1
kind: Deployment
metadata:
  name: arc-tomcat
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: arc-tomcat
        image: images-rc.canfar.net/skaha-system/cavern:0.4.8
      volumes:
      - name: cavern-ceph-volume
        cephfs:
          monitors:
          - 10.30.201.3:6789
          - 10.30.202.3:6789
          - 10.30.203.3:6789
          path: /volumes/_nogroup/dcd994bc-c0d4-4557-9fbf-28fc4ef5969e
          user: kanfarnetes_dev
          secretRef:
            name: cephfs-cephx-key
          readOnly: false
