namespace: skaha-system
resources:
- skaha-tomcat-deployment.yaml
- skaha-tomcat-expose.yaml
- skaha-ingress.yaml
configMapGenerator:
- name: skaha-config
  files:
  - config/catalina.properties
  - config/LocalAuthority.properties
  - config/RsaSignaturePub.key
  - config/launch-carta.yaml
  - config/launch-notebook.yaml
  - config/launch-desktop.yaml
  - config/launch-contributed.yaml
  - config/launch-headless.yaml
  - config/launch-desktop-app.yaml
  - config/k8s-resources.properties
  - config/service-notebook.yaml
  - config/ingress-notebook.yaml
  - config/service-desktop.yaml
  - config/ingress-desktop.yaml
  - config/service-carta.yaml
  - config/ingress-carta.yaml
  - config/service-contributed.yaml
  - config/ingress-contributed.yaml
generatorOptions:
 disableNameSuffixHash: true
