---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    canfar-net-sessionID: "${skaha.sessionid}"
    canfar-net-sessionName: "${skaha.sessionname}"
    canfar-net-sessionType: "${skaha.sessiontype}"
    canfar-net-userid: "${skaha.userid}"
  name: "${skaha.jobname}"
spec:
  activeDeadlineSeconds: 1209600
  ttlSecondsAfterFinished: 60
  backoffLimit: 0
  template:
    metadata:
      labels:
        canfar-net-sessionID: "${skaha.sessionid}"
        canfar-net-sessionName: "${skaha.sessionname}"
        canfar-net-sessionType: "${skaha.sessiontype}"
        canfar-net-userid: "${skaha.userid}"
        job-name: "${skaha.jobname}"
    spec:
      restartPolicy: Never
      ${skaha.schedulegpu}
      imagePullSecrets:
      - name: ${software.imagesecret}
      hostname: "${software.hostname}"
      securityContext:
        runAsUser: ${skaha.posixid}
        runAsGroup: ${skaha.posixid}
        fsGroup: ${skaha.posixid}
        supplementalGroups: [${skaha.supgroups}]
      containers:
      - name: "${skaha.jobname}"
        ${headless.image.bundle}
        securityContext:
          allowPrivilegeEscalation: false
        workingDir: "/arc/home/${skaha.userid}"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "${software.requests.ram}"
            cpu: "${software.requests.cores}"
            ephemeral-storage: "20Gi"
          limits:
            memory: "${software.limits.ram}"
            cpu: "${software.limits.cores}"
            nvidia.com/gpu: "${software.limits.gpus}"
            ephemeral-storage: "200Gi"
        volumeMounts:
        - mountPath: "/arc"
          name: cavern-volume
          subPath: "cavern"
        - mountPath: "/scratch"
          name: scratch-dir
          subPath: "${skaha.sessionid}"
        - mountPath: /var/lib/sss/pipes
          name: sssd-dir
          readOnly: true
      volumes:
      - name: cavern-volume
        cephfs:
          monitors:
          - 10.30.201.3:6789
          - 10.30.202.3:6789
          - 10.30.203.3:6789
          path: /volumes/_nogroup/dcd994bc-c0d4-4557-9fbf-28fc4ef5969e
          user: kanfarnetes_dev
          secretRef:
            name: cephfs-cephx-key
          readOnly: false          
      - name: scratch-dir
        emptyDir: {}
      - name: sssd-dir
        hostPath:
          path: /var/lib/ubernetes
          type: Directory
