apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cavern-ingress
  namespace: development
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /cavern/$2
spec:
  tls:
  - hosts:
    - proto.canfar.net
    secretName: canfar-net-cert-secret
  rules:
  - host: proto.canfar.net
    http:
      paths:
      - path: /cavern(/|$)(.*)
        backend:
          serviceName: cavern-tomcat-svc
          servicePort: 8080
