apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: servops-secrets-skaha-system-binding
  labels:
  {{- include "base.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'secrets-clusterrole'
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: servops
  namespace: '{{ .Release.Namespace }}'