apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: skaha-jobs-system-binding
  labels:
  {{- include "base.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'jobs-clusterrole'
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: canfarops
  namespace: '{{ .Release.Namespace }}'
- kind: ServiceAccount
  name: 'skaha'
  namespace: {{ .Values.skaha.namespace }}