apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ac-ingress
  namespace: skaha-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /ac/$2
    nginx.ingress.kubernetes.io/proxy-body-size: 100g
spec:
  rules:
  - host: keel-dev-ingress.cloud.computecanada.ca
    http:
      paths:
      - path: /ac(/|$)(.*)
        backend:
          serviceName: ac-tomcat-svc
          servicePort: 8080
